export const ListingStatus = {
    DRAFT: 'DRAFT',
    PUBLISHED: 'PUBLISHED',
    PAUSED: 'PAUSED',
    RESERVED: 'RESERVED',
    SOLD: 'SOLD',
    CANCELLED: 'CANCELLED'
};

export const OrderStatus = {
    CREATED: 'CREATED',
    CONFIRMED: 'CONFIRMED',
    PENDING: 'PENDING',
    PROCESSING: 'PROCESSING',
    SHIPPED: 'SHIPPED',
    DELIVERED: 'DELIVERED',
    CANCELLED: 'CANCELLED',
    COMPLETED: 'COMPLETED',
    WAREHOUSE_ASSIGNED: 'WAREHOUSE_ASSIGNED',
    WAITING_FOR_DISPATCH: 'WAITING_FOR_DISPATCH',
    COLLECTOR_ASSIGNED: 'COLLECTOR_ASSIGNED',
    COLLECTOR_ACCEPTED: 'COLLECTOR_ACCEPTED',
    TRAVELLING_TO_SELLER: 'TRAVELLING_TO_SELLER',
    ARRIVED_AT_PICKUP: 'ARRIVED_AT_PICKUP',
    MATERIAL_VERIFIED: 'MATERIAL_VERIFIED',
    PICKED_UP: 'PICKED_UP',
    IN_TRANSIT: 'IN_TRANSIT',
    ARRIVED_AT_BUYER: 'ARRIVED_AT_BUYER',
    BUYER_VERIFICATION: 'BUYER_VERIFICATION',
    WAREHOUSE_REJECTED: 'WAREHOUSE_REJECTED',
    COLLECTOR_DECLINED: 'COLLECTOR_DECLINED',
    BUYER_CANCELLED: 'BUYER_CANCELLED',
    SELLER_CANCELLED: 'SELLER_CANCELLED',
    DELIVERY_FAILED: 'DELIVERY_FAILED',
    REFUND_INITIATED: 'REFUND_INITIATED'
};

export const ReservationStatus = {
    ACTIVE: 'ACTIVE',
    RELEASED: 'RELEASED',
    EXPIRED: 'EXPIRED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    PENDING: 'PENDING',
    CONFIRMED: 'CONFIRMED'
};

export const PaymentStatus = {
    INITIATED: 'INITIATED',
    AUTHORIZED: 'AUTHORIZED',
    CAPTURED: 'CAPTURED',
    RELEASED: 'RELEASED',
    REFUNDED: 'REFUNDED',
    FAILED: 'FAILED',
    // Legacy statuses for backwards compatibility
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED'
};

export const PaymentMethod = {
    COD: 'COD',
    ONLINE: 'ONLINE',
    STRIPE: 'STRIPE'
};

export const PaymentProvider = {
    STRIPE: 'STRIPE',
    COD: 'COD'
};

export const UserRole = {
    INDIVIDUAL: 'individual',
    WAREHOUSE: 'warehouse',
    COMPANY: 'company',
    ADMIN: 'admin',
    COLLECTOR: 'collector'
};

export const VerificationStatus = {
    PENDING: 'PENDING',
    VERIFIED: 'VERIFIED',
    REJECTED: 'REJECTED',
    BLOCKED: 'BLOCKED',
    SUSPENDED: 'SUSPENDED'
};

export const KycStage = {
    REGISTERED: 'REGISTERED',
    DOCUMENTS_UPLOADED: 'DOCUMENTS_UPLOADED',
    VERIFIED: 'VERIFIED'
};

export const ItemStatus = {
    AVAILABLE: 'AVAILABLE',
    SOLD: 'SOLD',
    REMOVED: 'REMOVED'
};

export const TransactionStatus = {
    PENDING: 'PENDING',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED'
};

export const CollectorAvailability = {
    OFFLINE: 'OFFLINE',
    ONLINE: 'ONLINE',
    ON_DUTY: 'ON_DUTY',
    BUSY: 'BUSY',
    BREAK: 'BREAK'
};

export const CollectorTaskType = {
    SELLER_TO_WAREHOUSE: 'SELLER_TO_WAREHOUSE',
    SELLER_TO_BUYER: 'SELLER_TO_BUYER',
    WAREHOUSE_TO_BUYER: 'WAREHOUSE_TO_BUYER',
    BUYER_REQUESTED_PICKUP: 'BUYER_REQUESTED_PICKUP'
};

export const CollectorTaskStatus = {
    ASSIGNED: 'ASSIGNED',
    ACCEPTED: 'ACCEPTED',
    EN_ROUTE_TO_PICKUP: 'EN_ROUTE_TO_PICKUP',
    ARRIVED_AT_SOURCE: 'ARRIVED_AT_SOURCE',
    VERIFIED: 'VERIFIED',
    PICKED_UP: 'PICKED_UP',
    IN_TRANSIT: 'IN_TRANSIT',
    ARRIVED_AT_DESTINATION: 'ARRIVED_AT_DESTINATION',
    DELIVERED: 'DELIVERED',
    COMPLETED: 'COMPLETED',
    CANCELLED: 'CANCELLED',
    REJECTED: 'REJECTED'
};

export const WasteVerificationStatus = {
    PENDING: 'PENDING',
    VERIFIED: 'VERIFIED',
    FLAGGED: 'FLAGGED',
    REJECTED: 'REJECTED'
};

export const CollectorDeliveryStatus = {
    PENDING: 'PENDING',
    DELIVERED: 'DELIVERED',
    FAILED: 'FAILED'
};
